created: 2026-07-28T02:46:06.613Z
updated: 2026-07-28T02:46:09.902Z
update_count: 2
last_field: diagram
kind: nested-class
title: plug-api
children:
  - lib
  - syscall-bridge
  - syscalls
  - system-mock
  - types
  - ui
parentPath: []
