created: 2026-07-28T02:42:14.089Z
updated: 2026-07-28T02:42:26.189Z
update_count: 7
last_field: note
git_commit: eb0497b6
git_branch: local-mode-fs-access
children:
  - client
  - external
  - plug-api
  - plugs
  - sb-cli
  - server
  - server-bin
  - server-common
  - server-runtime-chrome
